### ISSUE TITLE
Alexandrite OS上でビルドに失敗する

### ISSUE THREAD

**Issue by Ljohske** [project-alexandrite/beaver#22]
### 問題
クリーンインストール後のAlexandrite OSで fedora をビルドしたところ

```
Error: Unable to find a match: basesystem dnf filesystem grub2-efi-x64 grub2-efi-x64-modules
```
[error.log](https://github.com/project-alexandrite/beaver/files/8192248/error.log)

というエラーが出てビルドに失敗します。

**Comment by Ljohske** [comment]
### P.S.
上記以外に以下の問題に遭遇しました。一時的にそれらに対処した方法とともに載せておきます。

1. targets/fedora/I18n/ja_JP/root の ディレクトリが存在しない旨のエラーが出てビルドに失敗<br>
→存在する `ja_JP` ディレクトリを削除し、Alexandrite OS のレシピから `ja_JP` のディレクトリをコピーして来ることで解決


2. `1` の解決後に 
```
KiwiCommandError: dnf: stderr: Errors during downloading metadata for repository '3c7606f46edcdeb8342bf9f5ec4ac0da':
  - Status code: 404 for https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/34/Everything/repodata/repomd.xml (IP: 152.19.134.145)
```
というエラーが出てビルドに失敗<br>
→ targets/fedora/base.conf の最終行、変数 `url1` を `https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/34/Everything/` から `https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/34/Everything/source/tree/` に書き換えることで解決<br>
(参照先: ` https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/34/Everything/repodata/repomd.xml` から [https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/34/Everything/source/tree/repodata/repomd.xml](https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/34/Everything/source/tree/repodata/repomd.xml) へ)

**Comment by nexryai** [comment]
報告ありがとうございます。ログを見る限り何らかの原因でdnfコマンドが正常にパッケージリポジトリを認識していないようです。レシピがFedora側の変更に対応できていない可能性があります。近日中に修正しますのでしばらくお待ちください。

**Comment by nexryai** [comment]
今までFedora35向けのdracut-kiwi-liveというパッケージがなかったのでFedora34のリポジトリを使用していましたが、先程確認するとFedora35向けのdracut-kiwi-liveが公式リポジトリに存在しました。これを期にFedora35のリポジトリに切り替えます。

**Comment by nexryai** [comment]
@Ljohske 
お待たせしました。以下のコミットで修正しました。
https://github.com/project-alexandrite/beaver/commit/8dee1df0e004270bc9911f67b4bfd95f1e50a4e0
https://github.com/project-alexandrite/beaver/commit/5c851e48290d0b67258560e6427881febec06dc2

**Comment by Ljohske** [comment]
ありがとうございます。
